disabled_rules: # rule identifiers to exclude from running
 - force_cast
 - line_length
 - trailing_whitespace
 - force_try
 - multiple_closures_with_trailing_closure

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Pods